version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Ensure it matches the Node.js version for Lambda
    commands:
      - echo "Installing dependencies..."
      - cd App_Backend
      - npm install
      - echo "Installing AWS SAM CLI..."
      - curl -Lo sam-cli.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip sam-cli.zip -d sam-installation
      - sudo ./sam-installation/install
      - sam --version

  pre_build:
    commands:
      - echo "Validating the SAM template..."
      - cd App_Backend
      - sam validate || { echo "Template validation failed. Exiting."; exit 1; }

  build:
    commands:
      - echo "Building the application..."
      - cd App_Backend
      - sam build --use-container

  post_build:
    commands:
      - echo "Deploying the application..."
      - cd App_Backend
      - sam deploy --no-confirm-changeset --stack-name my-sam-backend --region us-east-1
      - echo "Deployment complete."

artifacts:
  files:
    - template.yaml
    - samconfig.toml
    - App_Backend/app.js
    - App_Backend/index.js
    - App_Backend/package.json
    - App_Backend/package-lock.json
    - App_Backend/controllers/**
    - App_Backend/models/**
    - App_Backend/routes/**
    - App_Backend/middlewares/**
    - App_Backend/helpers/**
