version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Cleaning up existing node_modules..."
      - rm -rf App_Backend/node_modules
      - cd App_Backend
      - echo "Running npm ci to install dependencies..."
      - npm ci # Clean install to ensure all dependencies are correctly installed
      - cd ..
      - echo "Installing AWS SAM CLI..."
      - curl -Lo sam-cli.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip sam-cli.zip -d sam-installation
      - sudo ./sam-installation/install
      - sam --version

  pre_build:
    commands:
      - echo "Validating the SAM template..."
      - sam validate || { echo "Template validation failed. Exiting."; exit 1; }
      - echo "Verifying node_modules..."
      - ls -l App_Backend

  build:
    commands:
      - echo "Building the application..."
      - sam build --use-container

artifacts:
  files:
    - template.yaml
    - samconfig.toml
    - App_Backend/**
    - sam-installation/**
    - deployspec.yml # Include deployspec.yml in the artifacts
    - App_Backend/node_modules/** # Ensure node_modules is included in the build artifacts
